name: UAT Smoke

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  uat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps (export OpenAPI)
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          python - <<'PY'
from app.main import app
import json, os, sys
print("Exporting OpenAPI...")
open("openapi.json","w").write(json.dumps(app.openapi()))
print("Wrote openapi.json")
PY

      - name: Lint & type-check
        run: |
          pip install ruff mypy
          ruff check backend/app
          mypy --ignore-missing-imports backend/app

      - name: Build backend image
        run: docker build -f backend/Dockerfile -t estimator-backend:ci .

      - name: Run backend container
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CORS_ALLOW_ORIGINS: https://jcw-ai-estimator-frontend-fmthtgj3nq-uc.a.run.app
          STORAGE_BACKEND: local
          LOCAL_FILES_DIR: /tmp/jcw/uploads
        run: |
          docker run -d --rm -p 8080:8080             -e OPENAI_API_KEY             -e CORS_ALLOW_ORIGINS             -e STORAGE_BACKEND             -e LOCAL_FILES_DIR             --name estimator-backend estimator-backend:ci
          for i in {1..30}; do
            code=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8080/api/v2/health || true)
            if [ "$code" = "200" ]; then echo "Backend healthy"; break; fi
            sleep 2
          done

      - name: Smoke tests
        run: |
          chmod +x scripts/uat_smoke.sh
          BACKEND_URL=http://127.0.0.1:8080           FRONTEND_ORIGIN=https://jcw-ai-estimator-frontend-fmthtgj3nq-uc.a.run.app           ./scripts/uat_smoke.sh
